package mision_tic_2022_interfaces_graficas;
public class ayudareto5 extends javax.swing.JFrame {
    public ayudareto5() { //Constructor incluye todos los componentes
        initComponents();
        Paneles.setEnabledAt(0, true);
        Paneles.setEnabledAt(1, false);
        Paneles.setEnabledAt(2, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Paneles = new javax.swing.JTabbedPane();
        Panel1 = new javax.swing.JPanel();
        btnpanel1 = new javax.swing.JButton();
        Panel2 = new javax.swing.JPanel();
        Btnpanel2 = new javax.swing.JButton();
        Btnvolverpanel2 = new javax.swing.JButton();
        Panel3 = new javax.swing.JPanel();
        Btnvolverpanel3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Paneles.setBackground(new java.awt.Color(255, 153, 51));

        Panel1.setBackground(new java.awt.Color(51, 255, 51));

        btnpanel1.setText("SIGUIENTE");
        btnpanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpanel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(btnpanel1)
                .addContainerGap())
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(btnpanel1)
                .addContainerGap())
        );

        Paneles.addTab("PANEL 1", Panel1);

        Panel2.setBackground(new java.awt.Color(204, 102, 255));

        Btnpanel2.setText("SIGUIENTE");
        Btnpanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnpanel2ActionPerformed(evt);
            }
        });

        Btnvolverpanel2.setText("ATRAS");
        Btnvolverpanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnvolverpanel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btnvolverpanel2)
                    .addComponent(Btnpanel2))
                .addGap(19, 19, 19))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btnvolverpanel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(Btnpanel2)
                .addContainerGap())
        );

        Paneles.addTab("PANEL 2", Panel2);

        Panel3.setBackground(new java.awt.Color(255, 51, 0));

        Btnvolverpanel3.setText("ATRAS");
        Btnvolverpanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnvolverpanel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel3Layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(Btnvolverpanel3)
                .addGap(25, 25, 25))
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btnvolverpanel3)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        Paneles.addTab("PANEL 3", Panel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Paneles)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Paneles)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpanel1ActionPerformed
        // TODO add your handling code here:
        Paneles.setSelectedIndex(1);
        Paneles.setEnabledAt(1, true);
        Paneles.setEnabledAt(0, false);
        Paneles.setEnabledAt(2, false);
    }//GEN-LAST:event_btnpanel1ActionPerformed

    private void Btnvolverpanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnvolverpanel2ActionPerformed
        // TODO add your handling code here:
        Paneles.setSelectedIndex(0);
        Paneles.setEnabledAt(0, true);
        Paneles.setEnabledAt(1, false);
        Paneles.setEnabledAt(2, false);
    }//GEN-LAST:event_Btnvolverpanel2ActionPerformed

    private void Btnpanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnpanel2ActionPerformed
        // TODO add your handling code here:
        Paneles.setSelectedIndex(2);
        Paneles.setEnabledAt(2, true);
        Paneles.setEnabledAt(0, false);
        Paneles.setEnabledAt(1, false);
    }//GEN-LAST:event_Btnpanel2ActionPerformed

    private void Btnvolverpanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnvolverpanel3ActionPerformed
        // TODO add your handling code here:
        Paneles.setSelectedIndex(1);
        Paneles.setEnabledAt(1, true);
        Paneles.setEnabledAt(0, false);
        Paneles.setEnabledAt(2, false);
    }//GEN-LAST:event_Btnvolverpanel3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ayudareto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ayudareto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ayudareto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ayudareto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ayudareto5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnpanel2;
    private javax.swing.JButton Btnvolverpanel2;
    private javax.swing.JButton Btnvolverpanel3;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JTabbedPane Paneles;
    private javax.swing.JButton btnpanel1;
    // End of variables declaration//GEN-END:variables
}
