/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author loren
 */
public class Ejemplo_Visualizacion_dos extends javax.swing.JFrame {

    /**
     * Creates new form Ejemplo_Visualizacion_dos
     */
    public Ejemplo_Visualizacion_dos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CALCULADORApanel = new javax.swing.JPanel();
        calculadora = new javax.swing.JLabel();
        txtnumero1 = new javax.swing.JTextField();
        txtnumero2 = new javax.swing.JTextField();
        labelnumero1 = new javax.swing.JLabel();
        labelnumero2 = new javax.swing.JLabel();
        bntresta = new javax.swing.JButton();
        btnsuma = new javax.swing.JButton();
        btndividir = new javax.swing.JButton();
        btnmultiplicar = new javax.swing.JButton();
        txtresultado = new javax.swing.JTextField();
        labelresultado = new javax.swing.JLabel();
        btnlimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CALCULADORApanel.setBackground(new java.awt.Color(255, 204, 204));

        calculadora.setFont(new java.awt.Font("Candara", 2, 36)); // NOI18N
        calculadora.setText("CALCULADORA");

        txtnumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumero1ActionPerformed(evt);
            }
        });

        labelnumero1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelnumero1.setText("NUMERO1");

        labelnumero2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelnumero2.setText("NUMERO2");

        bntresta.setText("RESTA");
        bntresta.setToolTipText("");
        bntresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntrestaActionPerformed(evt);
            }
        });

        btnsuma.setText("SUMA");
        btnsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumaActionPerformed(evt);
            }
        });

        btndividir.setText("DIVIDIR");
        btndividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndividirActionPerformed(evt);
            }
        });

        btnmultiplicar.setText("MULTIPLICAR");
        btnmultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplicarActionPerformed(evt);
            }
        });

        txtresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresultadoActionPerformed(evt);
            }
        });

        labelresultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelresultado.setText("RESULTADO");

        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CALCULADORApanelLayout = new javax.swing.GroupLayout(CALCULADORApanel);
        CALCULADORApanel.setLayout(CALCULADORApanelLayout);
        CALCULADORApanelLayout.setHorizontalGroup(
            CALCULADORApanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CALCULADORApanelLayout.createSequentialGroup()
                .addGroup(CALCULADORApanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CALCULADORApanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(calculadora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnlimpiar))
                    .addGroup(CALCULADORApanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(CALCULADORApanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CALCULADORApanelLayout.createSequentialGroup()
                                .addGroup(CALCULADORApanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelnumero1))
                                .addGap(85, 85, 85)
                                .addGroup(CALCULADORApanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelnumero2)
                                    .addComponent(txtnumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CALCULADORApanelLayout.createSequentialGroup()
                                .addGroup(CALCULADORApanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CALCULADORApanelLayout.createSequentialGroup()
                                        .addComponent(btnsuma)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bntresta)
                                        .addGap(9, 9, 9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CALCULADORApanelLayout.createSequentialGroup()
                                        .addComponent(labelresultado)
                                        .addGap(18, 18, 18)))
                                .addGroup(CALCULADORApanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CALCULADORApanelLayout.createSequentialGroup()
                                        .addComponent(btnmultiplicar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btndividir))
                                    .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CALCULADORApanelLayout.setVerticalGroup(
            CALCULADORApanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CALCULADORApanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CALCULADORApanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculadora)
                    .addComponent(btnlimpiar))
                .addGap(18, 18, 18)
                .addGroup(CALCULADORApanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnumero1)
                    .addComponent(labelnumero2))
                .addGap(12, 12, 12)
                .addGroup(CALCULADORApanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(CALCULADORApanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntresta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsuma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndividir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CALCULADORApanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelresultado))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CALCULADORApanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CALCULADORApanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumero1ActionPerformed

    private void btnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumaActionPerformed
        // TODO add your handling code here:
        //declarar las variables
        int n1, n2, suma;
        //pasar de entero a String
        n1= Integer.parseInt(txtnumero1.getText());
        n2= Integer.parseInt(txtnumero2.getText());
        suma = n1+n2;
        //pasar de string a entero
        txtresultado.setText(String.valueOf(suma));
        
    }//GEN-LAST:event_btnsumaActionPerformed

    private void txtresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtresultadoActionPerformed

    private void bntrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntrestaActionPerformed
        // TODO add your handling code here:
        //declarar las variables
        int n1, n2, resta;
        //pasar de entero a String
        n1= Integer.parseInt(txtnumero1.getText());
        n2= Integer.parseInt(txtnumero2.getText());
        resta = n1-n2;
        //pasar de string a entero
        txtresultado.setText(String.valueOf(resta));
    }//GEN-LAST:event_bntrestaActionPerformed

    private void btnmultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplicarActionPerformed
        // TODO add your handling code here:
        //declarar las variables
        int n1, n2, multiplicar;
        //pasar de entero a String
        n1= Integer.parseInt(txtnumero1.getText());
        n2= Integer.parseInt(txtnumero2.getText());
        multiplicar = n1*n2;
        //pasar de string a entero
        txtresultado.setText(String.valueOf(multiplicar));
    }//GEN-LAST:event_btnmultiplicarActionPerformed

    private void btndividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndividirActionPerformed
        // TODO add your handling code here:
        //declarar las variables
        int n1, n2, dividir;
        //pasar de entero a String
        n1= Integer.parseInt(txtnumero1.getText());
        n2= Integer.parseInt(txtnumero2.getText());
        dividir = n1/n2;
        //pasar de string a entero
        txtresultado.setText(String.valueOf(dividir));
    }//GEN-LAST:event_btndividirActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        txtnumero2.setText(null);
        txtnumero1.setText(null);
        txtresultado.setText(null);
    }//GEN-LAST:event_btnlimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejemplo_Visualizacion_dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejemplo_Visualizacion_dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejemplo_Visualizacion_dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejemplo_Visualizacion_dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejemplo_Visualizacion_dos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CALCULADORApanel;
    private javax.swing.JButton bntresta;
    private javax.swing.JButton btndividir;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmultiplicar;
    private javax.swing.JButton btnsuma;
    private javax.swing.JLabel calculadora;
    private javax.swing.JLabel labelnumero1;
    private javax.swing.JLabel labelnumero2;
    private javax.swing.JLabel labelresultado;
    private javax.swing.JTextField txtnumero1;
    private javax.swing.JTextField txtnumero2;
    private javax.swing.JTextField txtresultado;
    // End of variables declaration//GEN-END:variables
}
